name: human_resource
description:  Human resource management project

version: 1.1.1+5

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6+3
  fluttertoast: ^4.0.1
  toast: ^0.1.5
  web_socket_channel: ^1.1.0
#  keyboard_visibility: ^0.5.2
#  flutter_audio_recorder: ^0.5.5
  intl: ^0.16.1
  dio: ^3.0.8
  just_audio: ^0.0.2
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  firebase_messaging: 6.0.13
  timeago: ^2.0.26
  cached_network_image: ^2.0.0
  camera: ^0.5.7+4
  path_provider: ^1.6.5
  url_launcher: ^5.4.2
  flutter_document_picker: ^4.0.0
  flutter_local_notifications: 0.8.4
  flutter_linkify: ^3.1.0
  flutter_screenutil: ^1.1.0
  flutter_downloader: ^1.4.1
  permission_handler: ^5.0.0
  table_calendar: ^2.0.1
  badges: ^1.1.1
  image_picker: ^0.6.4
  image_downloader: ^0.19.2
  flutter_slidable: ^0.5.4
  flutter_datetime_picker: ^1.3.5
  flutter_picker: ^1.1.3
  photo_view: ^0.9.2
  emoji_picker: ^0.1.0
  assorted_layout_widgets: ^1.0.18
  flutter_chips_input: ^1.8.1
  scrollable_positioned_list: ^0.1.5
  substring_highlight: ^0.1.2
  highlight_text: ^0.7.2
  hive: 1.1.1
  hive_flutter: ^0.3.0+2
  awsome_video_player: ^1.0.8+1
  liquid_pull_to_refresh: ^2.0.0
  shimmer: ^1.1.1
  flutter_barcode_scanner: ^1.0.1
  socket_io_client: ^0.9.10
  laravel_echo: ^0.2.2
  pdf_viewer_plugin: ^1.0.0+2
  flutter_html: 0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.5.1
  build_runner: ^1.10.0


flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - asset/images/action/
    - asset/font/
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: asset/font/Roboto-Regular.ttf

    - family: Roboto-Bold
      fonts:
        - asset: asset/font/Roboto-Bold.ttf

    - family: Roboto-Italic
      fonts:
        - asset: asset/font/Roboto-Italic.ttf



